name: Auto deply React to NCP

on:
  push:
    branches: "main"

jobs:
  push_to_registry:
    runs-on: ubuntu-20.04


    steps:
      - name: Checkout source code. 
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_API_KEY }}
          password: ${{ secrets.NCP_API_SECRET_KEY }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/weble-frontend:latest

  pull_deploy:
    name: Connect server ssh and pull from container registry
    needs: push_to_registry
    runs-on: ubuntu-20.04
    steps:
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: ${{ secrets.NCP_SERVER_NAME }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 22
          script: |
            echo "${{ secrets.NCP_API_SECRET_KEY }}" | docker login ${{ secrets.NCP_CONTAINER_REGISTRY }} -u ${{ secrets.NCP_API_KEY }} --password-stdin
            docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/weble-fontend:latest
            docker stop weble-frontend || true
            docker rm weble-frontend || true
            docker run -d --name weble-frontend -p 80:3000 ${{ secrets.NCP_CONTAINER_REGISTRY }}/weble-frontend:latest
            docker image prune -f
