name: React CI

on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code. 
        uses: actions/checkout@v3

      - name: Install node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Generate build
        run: npm run build
